import {
	ArrowRight,
	BarChart3,
	FileText,
	Mail,
	Megaphone,
	MessageCircle,
	PenTool,
} from "lucide-react";
import Link from "next/link";
import { Badge } from "../ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";

export const metadata = {
	title: "Examples - AI Content Generator",
	description:
		"Explore real examples of high-quality content generated by our AI across various formats and platforms. See how our AI can help you create engaging blog posts, social media content, email campaigns, ad copy, and more.",
};

const getIcon = (id) => {
	switch (id) {
		case "social":
			return MessageCircle;
		case "blog":
			return FileText;
		case "email":
			return Mail;
		case "ad":
			return Megaphone;
		case "sales":
			return BarChart3;
		case "creative":
			return PenTool;
		default:
			return FileText;
	}
};

const Examples = async ({ examples }) => {
	return (
		<section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
			<div className="text-center mb-16">
				<h2 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-4 text-foreground">
					See What You Can Create
				</h2>
				<p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto">
					Our AI generates high-quality content across multiple formats and
					platforms. Here are just some examples of what&apose;s possible.
				</p>
			</div>

			<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8 mb-16">
				{examples.map((example, index) => {
					const Icon = getIcon(example.id);
					return (
						<Link key={index} href={`/examples/${example.id}`}>
							<Card className="group border-border hover:shadow-2xl hover:-translate-y-2 transition-all duration-500 bg-card hover:bg-card/80 flex flex-col cursor-pointer h-full">
								<CardHeader className="pb-4">
									<div className="w-14 h-14 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:bg-primary/20 group-hover:scale-105 transition-all duration-400 border border-primary/20">
										<Icon className="w-7 h-7 text-primary group-hover:rotate-12 transition-all" />
									</div>
									<CardTitle className="text-xl lg:text-2xl font-bold group-hover:text-primary transition-colors">
										{example.title}
									</CardTitle>
									<p className="text-sm text-muted-foreground mt-2">
										{example.description}
									</p>
								</CardHeader>
								<CardContent className="grow">
									<ul className="space-y-3">
										{example.samples.map((sample, idx) => (
											<li key={idx} className="flex gap-2 items-start">
												<span className="text-primary mt-1 shrink-0">•</span>
												<span className="text-foreground/80 text-sm leading-relaxed">
													{sample}
												</span>
											</li>
										))}
									</ul>
								</CardContent>

								<div className="mt-auto px-6 pb-6">
									<button className="w-full flex items-center justify-between py-2 text-primary font-semibold group-hover:translate-x-1 transition-transform">
										View Full Example
										<ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
									</button>
								</div>
							</Card>
						</Link>
					);
				})}
			</div>

			<div className="bg-primary/5 rounded-3xl p-8 md:p-12 border border-primary/10">
				<div className="max-w-2xl mx-auto text-center">
					<h3 className="text-3xl md:text-4xl font-bold mb-4">
						Quality Content in Seconds
					</h3>
					<p className="text-lg text-muted-foreground mb-8">
						Our advanced AI algorithms analyze your requirements and generate
						perfectly tailored content that matches your brand voice, tone, and
						style preferences. Every piece is optimized for your target audience
						and platform.
					</p>
					<div className="flex flex-wrap gap-2 justify-center mb-8">
						<Badge>100% Unique</Badge>
						<Badge>SEO Optimized</Badge>
						<Badge>Brand Voice</Badge>
						<Badge>Plagiarism Free</Badge>
					</div>
					<p className="text-sm text-muted-foreground">
						Start creating amazing content today with our powerful AI content
						generator.
					</p>
				</div>
			</div>
		</section>
	);
};

export default Examples;
