import { ArrowRight } from "lucide-react";
import Link from "next/link";

const getId = (type, examples) => {
	const example = examples.find((ex) => ex.type.toLowerCase().startsWith(type));
	return example ? example.id : "";
};

const ShowCaseSection = ({ ids }) => {
	return (
		<section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
			<div className="bg-primary/5 rounded-3xl p-8 md:p-16 border border-primary/10">
				<div className="max-w-4xl mx-auto">
					<h2 className="text-4xl md:text-5xl font-bold mb-8 text-foreground">
						Real Examples from Real Users
					</h2>

					{/* Example 1 */}
					<div className="mb-12 p-6 bg-card rounded-2xl border border-border hover:shadow-lg transition-shadow">
						<div className="mb-4">
							<p className="text-sm font-semibold text-primary mb-2">
								Blog Post Example
							</p>
							<h3 className="text-2xl font-bold text-foreground mb-4">
								&ldquo;How to Implement Zero-Trust Security in Your
								Organization&rdquo;
							</h3>
						</div>
						<p className="text-muted-foreground leading-relaxed mb-4">
							Generated in 45 seconds • 2,500 words • SEO optimized • Ready to
							publish
						</p>
						<p className="text-foreground mb-4">
							&ldquo;This article was generated by our AI and required minimal
							editing. It ranked on page 1 of Google within 2 weeks and brought
							us 150+ qualified leads.&rdquo; - Sarah Chen, Security Consultant
						</p>
						<Link
							href={`/examples/${getId("blog", ids)}`}
							className="inline-flex items-center gap-2 text-primary hover:text-primary/80 font-semibold transition-colors"
						>
							View Full Example <ArrowRight className="w-4 h-4" />
						</Link>
					</div>

					{/* Example 2 */}
					<div className="mb-12 p-6 bg-card rounded-2xl border border-border hover:shadow-lg transition-shadow">
						<div className="mb-4">
							<p className="text-sm font-semibold text-primary mb-2">
								Social Media Campaign
							</p>
							<h3 className="text-2xl font-bold text-foreground mb-4">
								Twitter Thread: &ldquo;5 Ways to Scale Your SaaS Without Burning
								Out&rdquo;
							</h3>
						</div>
						<p className="text-muted-foreground leading-relaxed mb-4">
							Generated in 20 seconds • 12 tweets • High engagement format •
							Trending hashtags included
						</p>
						<p className="text-foreground mb-4">
							&ldquo;Our AI-generated threads consistently get 2-3x more
							engagement than our manually written ones. It&apos;s a
							game-changer for our social strategy.&rdquo; - Marcus Johnson,
							Growth Marketer
						</p>
						<Link
							href={`/examples/${getId("social", ids)}`}
							className="inline-flex items-center gap-2 text-primary hover:text-primary/80 font-semibold transition-colors"
						>
							View Full Example <ArrowRight className="w-4 h-4" />
						</Link>
					</div>

					{/* Example 3 */}
					<div className="p-6 bg-card rounded-2xl border border-border hover:shadow-lg transition-shadow">
						<div className="mb-4">
							<p className="text-sm font-semibold text-primary mb-2">
								Email Marketing
							</p>
							<h3 className="text-2xl font-bold text-foreground mb-4">
								Product Launch Email Sequence (5 emails)
							</h3>
						</div>
						<p className="text-muted-foreground leading-relaxed mb-4">
							Generated in 3 minutes • 5 emails • Custom brand voice •
							Personalization tokens included
						</p>
						<p className="text-foreground mb-4">
							&ldquo;We used the generated email sequence as a base and only
							made minor brand tweaks. Our open rate was 45% and CTR was
							12%.&rdquo; - Lisa Rodriguez, Email Marketing Manager
						</p>
						<Link
							href={`/examples/${getId("email", ids)}`}
							className="inline-flex items-center gap-2 text-primary hover:text-primary/80 font-semibold transition-colors"
						>
							View Full Example <ArrowRight className="w-4 h-4" />
						</Link>
					</div>
				</div>
			</div>
		</section>
	);
};

export default ShowCaseSection;
